import { environment } from "src/environments/environment";

export class EnumService {
  constructor() { }
}

export const commonURLs = environment.commonURLs;

export enum messageTypeEnum {
  Success = 1,
  Error = 2,
  Warning = 3,
  Info = 4,
  Wait = 5,
  default = 6,
}



export enum notificationMessageType {
  deletedSuccessfully = "Record has been deleted successfully",
  deletedFailed = "Record could not be deleted",
  deleteConfirmation = "Are you sure, you want to delete this record?",
  deleteAttachment = "Are you sure, you want to delete this attachment?",
  revertConfirmation = "Are you sure, you want to revert?",
  updateRecordSuccessfully = "Record has updated successfully",
  updateRecordFailed = "Update Record Failed",
  addRecordSuccessfully = "Record has added successfully",
  addRecordFailed = "Record could not be saved.",
  loadDataFailed = "Failed to load data",
  saveDataFailed = "Failed to save data",
  changesSaved = "Changes saved successfully",
  articleGenMessage = "Article Generation is started at background",
  sentEmail = "Email has sent!",
  EmailUserNameRequest = "Email for requested username has sent!",
  EmailPasswordRequest = "Email for requested password has sent!",
  fileUploadedSuccessfully = "File uploaded successfully!",
  importIdAlreadyExist = "Can not save the record becasue Import Id already exist",
  selectCategory = "Please select atleast one Category",
  selectAccountant = "Please select atleast one Accountant",
  selectQuestion = "Please select atleast one Question",
  selectSubject = "Please select atleast one Subject",
  DP2RequestQueued = "Request Queued successfully",
  copyConceptConfirmation = "Are you sure, you want to use the same name for concept?",
  GetRecordFailed = "Get Record Failed",
  FillFields = "Please fillout all fields Properly",
  selectTemplateType = "Please select one Template Type",
  selectAccountantTemplateType = "Please select one Accountant and one Template Type",
  fileSelect = "Please Choose at least one File!",
  recordSaved = "Saved successfully",
  SyncRecord = "sync record successfully",
  proofingExpire = "Proofing End Date Updated",
  SelectName = "Please Select Name",
  SelectFriendlyName = "Please Select Friendly Name",
  proofing = "Proofing sent Successfully!",
  DP2NewConceptCreation = "Concept saved successfully!",
  DigiPrintSelection = "Done successfully!",
  editConfirmation = "Are you sure, you want to edit this record?",
  fieldsNotSelected = "Please check you input selection(s)",
  revertStatusLiveConfirmation = "Are you sure, you want to revert the stautus to live?",
  revertStatusOfflineConfirmation = "Are you sure, you want to revert the stautus to offline?",
  editSurveyFailedNotEligibleMessage = "Please change status to offline for edit the intended record.",
  orphanImageLinksRemoved = "Orphan images removed",
  removeConfirmation = "Are you sure, you want to remove content from this subject record?",
  removeSuccessfully = "Record has been remove from this subject successfully",
  placeOrder = "Order Placed Successfully",
  clearAllQuestions = "Are you sure, you want to clear all questions?",
  addQuestions = "Please add one or more questions",
  noResponseForSurveyYetRecorded = "No responses yet for this survey",
  newResponseNotifyMessage = "New response is recorded",
  isPublishedResponseNotifyMessage = "Template has been published successfully",
  fillFieldProperly = "Please fill Fields Properly",
  alreadySubscribed = "already Subscribed",
  wrongEmail = "Please validate email address",
  editTemplate = "Are you sure you want to change this template?",
  useThisTemplateForComparison = "Are you sure you want to use this template for comparison?",
  restoreThisTemplate = "Are you sure you want to use restore this template?",
  publishTemplate = "Are you sure you want to publish this template?",
  OfficeCreation = "Please create office first",
  duplicateConfirmation = "Are you sure, you want to duplicate  this template?",

  createOrder = "Order is created successfully",
  createOrderFailed = "Error while creating the order.",
  placeOrderFailed = "Error while placing the order.",
  cartUpdate = "Cart is updated successfully.",
  cartEmpty = "Cart is empty.",
  cartUpdateFailed = "Error while updating the cart.",
  cartUpdateNotExists = "Please create a new order.",
  cartUpdateNotFound = "Error while locating the cart.",
  cartItemSelectForDelete = "Please select an cart item for delete.",
  cartMinimumQuantityPerItem = "Minimum quantity is ",
  selectAccountantStyle = "Please select an accountant style",
  importConfirmationMessage = "Do you want to import?",
  GenerateArticle = 'Generating AI Article in Background',
  ErrorLoadingAIArticle = 'Error loading AI article data',
  errorSavingOffice = 'Error saving office data',
}

export enum notificationMessageHeader {
  deleteRecordSummary = "Delete",
  updateRecordSummary = "Update",
  saveRecordSummary = "Save",
  addRecordSummary = "Add",
  confirmationSummary = "Confirmation",
  nullDataSummary = "Record Not Found",
  removeRecordSummary = "Remove",
  SyncRecordSummary = "Sync",
  errorSeverity = "error",
  errorSummary = "Error",
  warningSeverity = 'warn',
  warningSummary = "Warn",
  infoSeverity = "info",
  infoSummary = "Info",
  successSummary = "Success",
  successSeverity = "success",

}
